/*

AUTORES:
	AYALA HERNÁNDEZ MARÍA FERNANDA
    PORTILLA HERMENEGILDO ELIZABETH
    VALENZUELA ASCENCIO GUSTAVO
    JIMENEZ AYALA YORDI JOSUE

FECHA DE CREACION: 18 DE MAYO DE 2025

ULTIMA ACTUALIZACION: 18 DE MAYO DE 2025 

DESCRIPCION: DCL QUE CONTIENE LA CREACION DE USUARIOS PARA LA GESTION DE LA BASE

*/

-- SELECCIONAMOS NUESTRA BASE PARA TRABAJAR SOBRE ELLA

USE Equipo09AppSafe
GO

-- CREAMOS LOS ROLES QUE VAMOS A USAR EN LA BASE

CREATE ROLE ADMINISTRADOR
CREATE ROLE CONDUCTOR
CREATE ROLE CLIENTE
CREATE ROLE ANALISTA

-- OTORGAMOS PERMISOS A LOS ROLES


-- 1) OTORGANDO PERMISOS DE LECTURA 

GRANT SELECT ON ACCIDENTE TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON ADMINISTRADOR TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON [AUTO] TO ANALISTA, ADMINISTRADOR, CONDUCTOR
GO

GRANT SELECT ON BANCO TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON CLIENTE TO ANALISTA, ADMINISTRADOR, CLIENTE
GO

GRANT SELECT ON CONDUCTOR TO ANALISTA, ADMINISTRADOR, CONDUCTOR
GO

GRANT SELECT ON DESCUENTO TO ANALISTA, ADMINISTRADOR, CLIENTE
GO

GRANT SELECT ON DESCUENTO_ADMIN TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON ESTATUS TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON ETIQUETA TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON FACTURA TO ANALISTA, ADMINISTRADOR, CLIENTE
GO

GRANT SELECT ON MARCA TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON MODELO TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON PAGO TO ANALISTA, ADMINISTRADOR, CONDUCTOR
GO

GRANT SELECT ON QUEJA TO ANALISTA, ADMINISTRADOR, CLIENTE, CONDUCTOR
GO

GRANT SELECT ON TARJETA TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON TELEFONO TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON TIPO TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON TIPO_ACCIDENTE TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON UBICACION TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON USUARIO TO ANALISTA, ADMINISTRADOR
GO

GRANT SELECT ON VIAJE TO ANALISTA, ADMINISTRADOR, CLIENTE
GO

GRANT SELECT ON VIAJE_ESTATUS TO ANALISTA, ADMINISTRADOR
GO

-- 2) OTORGANDO PERMISOS DE INSERTAR

GRANT INSERT ON ACCIDENTE TO ADMINISTRADOR
GO

GRANT INSERT ON ADMINISTRADOR TO ADMINISTRADOR
GO

GRANT INSERT ON [AUTO] TO ADMINISTRADOR, CONDUCTOR
GO

GRANT INSERT ON BANCO TO ADMINISTRADOR
GO

GRANT INSERT ON CLIENTE TO ADMINISTRADOR
GO

GRANT INSERT ON CONDUCTOR TO ADMINISTRADOR
GO

GRANT INSERT ON DESCUENTO TO ADMINISTRADOR
GO

GRANT INSERT ON DESCUENTO_ADMIN TO ADMINISTRADOR
GO

GRANT INSERT ON ESTATUS TO ADMINISTRADOR
GO

GRANT INSERT ON ETIQUETA TO ADMINISTRADOR
GO

GRANT INSERT ON FACTURA TO ADMINISTRADOR, CLIENTE
GO

GRANT INSERT ON MARCA TO ADMINISTRADOR
GO

GRANT INSERT ON MODELO TO ADMINISTRADOR
GO

GRANT INSERT ON PAGO TO ADMINISTRADOR
GO

GRANT INSERT ON QUEJA TO ADMINISTRADOR, CLIENTE
GO

GRANT INSERT ON TARJETA TO ADMINISTRADOR, CLIENTE
GO

GRANT INSERT ON TELEFONO TO ADMINISTRADOR
GO

GRANT INSERT ON TIPO TO ADMINISTRADOR
GO

GRANT INSERT ON TIPO_ACCIDENTE TO ADMINISTRADOR
GO

GRANT INSERT ON UBICACION TO ADMINISTRADOR
GO

GRANT INSERT ON USUARIO TO ADMINISTRADOR
GO

GRANT INSERT ON VIAJE TO ADMINISTRADOR, CLIENTE
GO

GRANT INSERT ON VIAJE_ESTATUS TO ADMINISTRADOR
GO

-- 3) OTORGANDO PERMISOS DE ACTUALIZAR

GRANT UPDATE ON ACCIDENTE TO ADMINISTRADOR
GO

GRANT UPDATE ON ADMINISTRADOR TO ADMINISTRADOR
GO

GRANT UPDATE ON [AUTO] TO ADMINISTRADOR
GO

GRANT UPDATE ON BANCO TO ADMINISTRADOR
GO

GRANT UPDATE ON CLIENTE TO ADMINISTRADOR
GO

GRANT UPDATE ON CONDUCTOR TO ADMINISTRADOR
GO

GRANT UPDATE ON DESCUENTO TO ADMINISTRADOR
GO

GRANT UPDATE ON DESCUENTO_ADMIN TO ADMINISTRADOR
GO

GRANT UPDATE ON ESTATUS TO ADMINISTRADOR
GO

GRANT UPDATE ON ETIQUETA TO ADMINISTRADOR
GO

GRANT UPDATE ON FACTURA TO ADMINISTRADOR
GO

GRANT UPDATE ON MARCA TO ADMINISTRADOR
GO

GRANT UPDATE ON MODELO TO ADMINISTRADOR
GO

GRANT UPDATE ON PAGO TO ADMINISTRADOR
GO

GRANT UPDATE ON QUEJA TO ADMINISTRADOR
GO

GRANT UPDATE ON TARJETA TO ADMINISTRADOR
GO

GRANT UPDATE ON TELEFONO TO ADMINISTRADOR
GO

GRANT UPDATE ON TIPO TO ADMINISTRADOR
GO

GRANT UPDATE ON TIPO_ACCIDENTE TO ADMINISTRADOR
GO

GRANT UPDATE ON UBICACION TO ADMINISTRADOR
GO

GRANT UPDATE ON USUARIO TO ADMINISTRADOR
GO

GRANT UPDATE ON VIAJE TO ADMINISTRADOR
GO

GRANT UPDATE ON VIAJE_ESTATUS TO ADMINISTRADOR
GO

-- 4) OTORGANDO PERMISOS DE ACTUALIZAR

GRANT DELETE ON ACCIDENTE TO ADMINISTRADOR
GO

GRANT DELETE ON ADMINISTRADOR TO ADMINISTRADOR
GO

GRANT DELETE ON [AUTO] TO ADMINISTRADOR
GO

GRANT DELETE ON BANCO TO ADMINISTRADOR
GO

GRANT DELETE ON CLIENTE TO ADMINISTRADOR
GO

GRANT DELETE ON CONDUCTOR TO ADMINISTRADOR
GO

GRANT DELETE ON DESCUENTO TO ADMINISTRADOR
GO

GRANT DELETE ON DESCUENTO_ADMIN TO ADMINISTRADOR
GO

GRANT DELETE ON ESTATUS TO ADMINISTRADOR
GO

GRANT DELETE ON ETIQUETA TO ADMINISTRADOR
GO

GRANT DELETE ON FACTURA TO ADMINISTRADOR
GO

GRANT DELETE ON MARCA TO ADMINISTRADOR
GO

GRANT DELETE ON MODELO TO ADMINISTRADOR
GO

GRANT DELETE ON PAGO TO ADMINISTRADOR
GO

GRANT DELETE ON QUEJA TO ADMINISTRADOR
GO

GRANT DELETE ON TARJETA TO ADMINISTRADOR
GO

GRANT DELETE ON TELEFONO TO ADMINISTRADOR
GO

GRANT DELETE ON TIPO TO ADMINISTRADOR
GO

GRANT DELETE ON TIPO_ACCIDENTE TO ADMINISTRADOR
GO

GRANT DELETE ON UBICACION TO ADMINISTRADOR
GO

GRANT DELETE ON USUARIO TO ADMINISTRADOR
GO

GRANT DELETE ON VIAJE TO ADMINISTRADOR
GO

GRANT DELETE ON VIAJE_ESTATUS TO ADMINISTRADOR
GO


-- DANDOLE EL RESTO DE PERMISOS AL ADMIN QUE ES LA MAXIMA AUTORIDAD EN LA BASE 

GRANT ALTER ANY USER TO ADMINISTRADOR; -- CREACION, MODIFICACION, ETC DE USUARIOS
GRANT ALTER ANY ROLE TO ADMINISTRADOR; -- AGREGAR MIEMBROS A ROLES
GRANT CREATE PROCEDURE TO ADMINISTRADOR; -- CREAR PROCEDIMIENTOS



-- CREAMOS ALGUNOS USUARIOS

CREATE LOGIN marthaAnalista WITH PASSWORD = N'qwe321r', DEFAULT_DATABASE = [Equipo09AppSafe], CHECK_EXPIRATION = OFF
GO
CREATE USER marthaAnalista FOR LOGIN marthaAnalista
GO
ALTER ROLE ANALISTA ADD MEMBER marthaAnalista
GO

CREATE LOGIN maferAdmin WITH PASSWORD = N'789qwez', DEFAULT_DATABASE = [Equipo09AppSafe], CHECK_EXPIRATION = OFF
GO
CREATE USER maferAdmin FOR LOGIN maferAdmin
GO
ALTER ROLE ADMINISTRADOR ADD MEMBER maferAdmin
GO

CREATE LOGIN eliAdmin WITH PASSWORD = N'1a2b3cd', DEFAULT_DATABASE = [Equipo09AppSafe], CHECK_EXPIRATION = OFF
GO
CREATE USER eliAdmin FOR LOGIN eliAdmin
GO
ALTER ROLE ADMINISTRADOR ADD MEMBER eliAdmin
GO

CREATE LOGIN gusAdmin WITH PASSWORD = N'pass456', DEFAULT_DATABASE = [Equipo09AppSafe], CHECK_EXPIRATION = OFF
GO
CREATE USER gusAdmin FOR LOGIN gusAdmin
GO
ALTER ROLE ADMINISTRADOR ADD MEMBER gusAdmin
GO

CREATE LOGIN yordiAdmin WITH PASSWORD = N'zxc987m', DEFAULT_DATABASE = [Equipo09AppSafe], CHECK_EXPIRATION = OFF
GO
CREATE USER yordiAdmin FOR LOGIN yordiAdmin
GO
ALTER ROLE ADMINISTRADOR ADD MEMBER yordiAdmin
GO



